trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectPath: 'Src/Entry/Entry.csproj'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'

steps:
  # 1. Fetch full history
  - checkout: self
    fetchDepth: 0

  # 2. Cài .NET SDK (nếu cần)
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # 3. Restore
  - script: dotnet restore $(projectPath)
    displayName: 'Restore Dependencies'

  # 4. Build
  - script: dotnet build $(projectPath) --configuration $(buildConfiguration) --no-restore
    displayName: 'Build Project'

  # 5. Publish
  - script: dotnet publish $(projectPath) --configuration $(buildConfiguration) --output $(publishDir) --no-restore --self-contained false
    displayName: 'Publish Project'

  # 6. SSH Deploy to VPS
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: '20.2.88.32'
      sshPublicKey: '$(sshPublicKey)' # hoặc không cần nếu dùng password auth
      sshKeySecureFile: 'vps-private-key.pem' # Tên file SSH key đã upload lên Azure
      passphrase: '' # nếu không có pass

  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'UMLVPS' # service connection đã tạo
      sourceFolder: '$(publishDir)'
      contents: '**'
      targetFolder: '/home/vuvudev/apps/umlbasicaiapi/production'

  - task: SSH@0
    inputs:
      sshEndpoint: 'UMLVPS'
      runOptions: 'commands'
      commands: |
        sudo systemctl daemon-reload
        sudo systemctl restart umlbasicaiapi
        sudo systemctl status umlbasicaiapi --no-pager
