trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectPath: 'Src/Entry/Entry.csproj'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'

steps:
  - checkout: self
    fetchDepth: 0

  - task: UseDotNet@2
  displayName: 'Use .NET Core SDK 8.0.x'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: SonarCloudPrepare@1
displayName: 'SonarCloud Prepare'
    inputs:
      SonarCloud: 'SonarConnection'
      organization: 'vuvvde170201'
      scannerMode: 'MSBuild'
      projectKey: 'vuvvde170201_UMLBasicAI_API'
      projectName: 'UMLBasicAI_API'
  - script: dotnet restore $(projectPath)
    displayName: 'Restore Dependencies'

  - script: dotnet build $(projectPath) --configuration $(buildConfiguration) --no-restore
    displayName: 'Build Project'

  - task: SonarCloudAnalyze@1
    displayName: 'SonarCloud Analyze'

  - task: SonarCloudPublish@1
    displayName: 'SonarCloud Publish'
    inputs:
      pollingTimeoutSec: '300'

  - script: dotnet publish $(projectPath) --configuration $(buildConfiguration) --output $(publishDir) --no-restore --self-contained false
    displayName: 'Publish Project'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(publishDir)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/umlbasicaiapi.zip'
      replaceExistingArchive: true

  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'AzureVPS'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
      contents: 'umlbasicaiapi.zip'
      targetFolder: '/home/vuvudev/apps/umlbasicaiapi'

  - task: SSH@0
displayName: 'Extract app on Azure VPS'
    inputs:
      sshEndpoint: 'AzureVPS'
      runOptions: 'commands'
      commands: |
        unzip -o /home/vuvudev/apps/umlbasicaiapi/umlbasicaiapi.zip -d /home/vuvudev/apps/umlbasicaiapi/production
        rm /home/vuvudev/apps/umlbasicaiapi/umlbasicaiapi.zip

  - task: SSH@0
    displayName: 'Restart app on Azure VPS'
    inputs:
      sshEndpoint: 'AzureVPS'
      runOptions: 'commands'
      commands: |
        sudo systemctl daemon-reload
        sudo systemctl restart umlbasicaiapi
        sudo systemctl status umlbasicaiapi --no-pager
