trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectPath: 'Src/Entry/Entry.csproj'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'

steps:
  # 1. Fetch full history
  - checkout: self
    fetchDepth: 0

  # 2. Cài .NET SDK (nếu cần)
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # 3. Restore
  - script: dotnet restore $(projectPath)
    displayName: 'Restore Dependencies'

  # 4. Build
  - script: dotnet build $(projectPath) --configuration $(buildConfiguration) --no-restore
    displayName: 'Build Project'

  # 5. Publish
  - script: dotnet publish $(projectPath) --configuration $(buildConfiguration) --output $(publishDir) --no-restore --self-contained false
    displayName: 'Publish Project'

    # 6. Nén thư mục publish thành file zip
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(publishDir)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/umlbasicaiapi.zip'
      replaceExistingArchive: true

  # 7. Copy file zip sang VPS
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'AzureVPS'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
      contents: 'umlbasicaiapi.zip'
      targetFolder: '/home/vuvudev/apps/umlbasicaiapi'

  # 8. SSH giải nén và restart service
  - task: SSH@0
    inputs:
      sshEndpoint: 'AzureVPS'
      runOptions: 'commands'
      commands: |
        unzip -o /home/vuvudev/apps/umlbasicaiapi/umlbasicaiapi.zip -d /home/vuvudev/apps/umlbasicaiapi/production
        rm /home/vuvudev/apps/umlbasicaiapi/umlbasicaiapi.zip
        sudo systemctl daemon-reload
        sudo systemctl restart umlbasicaiapi
        sudo systemctl status umlbasicaiapi --no-pager


  - task: SSH@0
    inputs:
      sshEndpoint: 'AzureVPS'
      runOptions: 'commands'
      commands: |
        sudo systemctl daemon-reload
        sudo systemctl restart umlbasicaiapi
        sudo systemctl status umlbasicaiapi --no-pager
